homeassistant:
  name: Snode
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

http:
  #base_url: !secret http_base_url
  #api_password: !secret http_api_password
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  #ip_ban_enabled: True
  #login_attempts_threshold: 3

frontend:

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
#discovery:
updater:
sun:

wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

ecobee:
  api_key: !secret ecobee_key
#ifttt:
 # key: !secret ifttt_key

logbook:
  exclude:
    entities:
      - media_player.htc_one_m9
      - media_player.htc_one_m9__0pja2


history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date

#logger: !include logger.yaml
#recorder: !include recorder.yaml

#mqtt:
  #broker: 127.0.0.1
  #port: 1883
  #client_id: home-assistant
  #username: !secret MQTT_username
  #password: !secret MQTT_password

zwave:
  usb_path: /dev/zwave
zigbee:
  device: /dev/zigbee

media_player:
  - platform: cast
  - platform: plex
#    entity_namespace: 'plex'

tts:
  platform: google

#Emulated Hue
emulated_hue:
  host_ip: 192.168.1.245
  listen_port: 80
  expose_by_default: false

#sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
#scene: !include_dir_merge_list scene
#switch: !include_dir_merge_list switch
#script: !include_dir_merge_named script
#input_boolean: !include_dir_merge_named input_boolean
#input_select: !include_dir_merge_named input_select
#shell_command: !include_dir_merge_named shell_command
