- alias: Welcome Family
  trigger:
    - platform: state
      entity_id:
        - device_tracker.stephen
      from: 'not_home'
      to: 'home'
  action:
    - service: tts.google_say
      entity_id: media_player.family_room_home
      data_template:
        message: "Welcome home, {{ trigger.entity_id.split('.')[1].split('_')[1] }}!"