################################################
## Sensor
################################################
sensor:
  - platform: command_line
    name: family_room_tv
    command: >-
      ssh hdmicec 'echo pow 0 | cec-client -s -d 1'
    scan_interval: 900