################################################################
## Packages / Radio
################################################################
homeassistant:
  customize:
    script.radio:
      friendly_name: Start Radio
      icon: mdi:radio

script:
  radio:
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: >
            media_player.family_room_home
          volume_level: '0.55'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.family_room_home
          media_content_id: http://54.198.252.60/entercom-kmbzfmmp3-64
          app_name: TuneIn Free
          app_id: 12F05308
  ###### VOLUME SLIDER CONTROL (LOCATION BASED)
#  radio_volume:


input_select:
  radio_station:
    name: Radio Station
    options:
      - "-"
      - Hot 108
      - The Beat
      - Alt Rock
      - Rock Radio
      - Energy 98
      - Hit Remixes
      - Play Radio
      - 90s Hits
      - Elium-Rock
      - KMBZ
    initial: "-"
    icon: mdi:radio
  radio_station_location:
    name: Radio Location
    options:
      - Family Room Soundbar
      - Family Room Home
      - All Zones
    initial: "Family Room Home"
    icon: mdi:radio

input_slider:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05